name: honey
description: The sweet side of testing. An end to end testing framework for Flutter.
version: 0.1.2
homepage: https://honey.dev
repository: https://github.com/clickup/honey

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  antlr4: ^4.11.1
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  very_good_analysis: ^3.1.0
